name: whatsapp_stickers_injector
description: A Flutter plugin for adding stickers to WhatsApp from any Flutter app.
version: 1.1.4
homepage: https://github.com/tomerof/whatsapp_stickers_injector

environment:
  sdk: '>=2.16.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  change_app_package_name: ^1.4.0
  flutter:
    sdk: flutter
  meta: ^1.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.liatofer.whatsapp_stickers_injector
        pluginClass: WhatsappStickersPlugin
      ios:
        pluginClass: WhatsappStickersPlugin
